name: Suggest a Library
description: Suggest an ECS library, game engine, or tool to add to the list
title: "[Suggestion] "
labels: ["suggestion"]
body:
  - type: input
    id: name
    attributes:
      label: Library Name
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: Project website or repository URL
    validations:
      required: true

  - type: input
    id: github
    attributes:
      label: GitHub Repository
      description: "GitHub `owner/repo` slug (e.g., `skypjack/entt`). Leave blank if the project is not on GitHub."
      placeholder: owner/repo

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - "ECS Libraries: C/C++"
        - "ECS Libraries: C#"
        - "ECS Libraries: Common Lisp"
        - "ECS Libraries: Dart"
        - "ECS Libraries: Elixir"
        - "ECS Libraries: Python"
        - "ECS Libraries: Rust"
        - "ECS Libraries: Go"
        - "ECS Libraries: Lua"
        - "ECS Libraries: Java"
        - "ECS Libraries: Julia"
        - "ECS Libraries: Kotlin"
        - "ECS Libraries: JavaScript / TypeScript"
        - "ECS Libraries: Zig"
        - "ECS Libraries: Haskell"
        - "ECS Libraries: Other Language"
        - "Game Engines"
        - "Graphics Engines"
        - "Physics Libraries"
        - "Benchmarks"
        - "New Category"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of what this library does
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why should it be included?
      description: Explain what makes this library a good fit for the list (e.g., fills a gap, widely used, novel approach).

  - type: checkboxes
    id: must_have
    attributes:
      label: "Must-have checklist (all required)"
      description: "All four must be checked for acceptance."
      options:
        - label: Relevant to ECS (entity-component-system pattern, data-oriented design, or ECS-powered application)
        - label: Publicly accessible (open source, or well-documented commercial tool)
        - label: Not a duplicate of an existing entry
        - label: Has a meaningful description

  - type: checkboxes
    id: scoring
    attributes:
      label: "Scoring checklist (need ≥ 3 of 5)"
      description: "Check all that apply. We will verify these during review."
      options:
        - label: "**Popularity**: ≥ 50 GitHub stars (or equivalent community adoption)"
        - label: "**Activity**: At least one commit within the last 2 years"
        - label: "**Documentation**: Has a README with usage examples or API docs"
        - label: "**Maturity**: Project is ≥ 6 months old"
        - label: "**Uniqueness**: Fills a niche not already covered by existing entries"
